### ISSUE TITLE
First setup

### ISSUE THREAD

**Issue by devilmind81** [nekef/ESP32-WI-FI-Deauther#1]
How can I flash and prepare my ESP32 to run .ino file?
Can you explain how can I setup it pls?

Thanks in advance

**Comment by nekef** [comment]
1. Install Required Software:
Ensure you have the necessary software installed on your computer. You'll need the Arduino IDE, which you can download from the official Arduino website. Additionally, you'll need the ESP32 board support package for the Arduino IDE. You can install it through the Arduino Boards Manager.

2. Select ESP32 Board in Arduino IDE:
Open the Arduino IDE and go to Tools > Board. From the dropdown menu, select the ESP32 board that you are using. Make sure to choose the correct variant and port.

3. Install USB to UART Driver:
If you are using a development board with a USB to UART converter (like the NodeMCU ESP-32), install the necessary USB to UART driver for your operating system.You can get the driver at https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads

4. Connect ESP32 to Computer:
Connect your ESP32 to your computer using a USB cable. Ensure that the device is recognized by your computer.

5. Set Upload Speed and Flash Mode:
In the Arduino IDE, go to Tools > Upload Speed and choose an appropriate speed. Additionally, set the Tools > Flash Mode to QIO or DIO, depending on your ESP32 board.

6. Upload .ino File:
Open the WI-FI_Deauther.ino file in the Arduino IDE and click the upload button (right arrow icon). The IDE will compile the code and upload it to your ESP32. Monitor the progress in the console window.

7. Verify and Monitor:
After the upload is complete, open the Serial Monitor (Tools > Serial Monitor) to verify that your ESP32 is running as expected. You can use Serial.print statements in your code to output information to the Serial Monitor.
